# -*- coding: utf-8 -*-
"""CV-CO1-AT1-QN3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apa9ZuuAXe2qi61553KcS2LzMr2Asumx
"""

import numpy as np
import matplotlib.pyplot as plt

# Generate a high-frequency checkerboard image
size = 256
frequency = 32

x = np.arange(size)
y = np.arange(size)
X, Y = np.meshgrid(x, y)

checkerboard = ((np.sin(2 * np.pi * frequency * X / size) *
                 np.sin(2 * np.pi * frequency * Y / size)) > 0).astype(float)

# -----------------------------
# Aliasing by undersampling
# -----------------------------
sample_factor = 8

# Downsample
downsampled = checkerboard[::sample_factor, ::sample_factor]

# Upsample back using nearest neighbor
aliased = np.repeat(np.repeat(downsampled, sample_factor, axis=0),
                    sample_factor, axis=1)

aliased = aliased[:size, :size]

# -----------------------------
# Corrected image
# -----------------------------
correct_factor = 2

downsampled_correct = checkerboard[::correct_factor, ::correct_factor]

corrected = np.repeat(np.repeat(downsampled_correct, correct_factor, axis=0),
                      correct_factor, axis=1)

corrected = corrected[:size, :size]

# -----------------------------
# Display Results
# -----------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(checkerboard, cmap='gray')
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(aliased, cmap='gray')
plt.title("Aliased Image\n(Undersampling)")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(corrected, cmap='gray')
plt.title("Corrected Image\n(Higher Sampling)")
plt.axis('off')

plt.tight_layout()
plt.show()

# -----------------------------
# Explanation
# -----------------------------
print("CAUSE OF ALIASING:")
print("- The image contains high-frequency details.")
print("- Sampling with a very low sampling rate violates the Nyquist criterion.")
print("- High-frequency information appears as false patterns (aliasing).")

print("\nQUANTIZATION:")
print("- Quantization reduces intensity levels.")
print("- It mainly causes banding or loss of gray levels, not aliasing.")

print("\nCORRECTIVE APPROACH:")
print("- Increase the sampling rate.")
print("- Apply an anti-aliasing (low-pass) filter before downsampling.")
print("- Follow the Nyquist sampling criterion.")
